import type { AchievementDefinition } from './gamificationTypes';

/**
 * Static achievement catalog seeded idempotently into the database.
 * Keys and criteria are persisted — only presentation fields may evolve.
 * Cosmic tiers: Orbit (bronze) → Stellar (silver) → Nebula (gold) → Event Horizon (legendary).
 */
export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // Retrieval — memory as orbital reinforcement
  {
    key: 'first_recall',
    title: 'First Echo',
    description: 'Catch the first returning signal from an object in orbit.',
    category: 'retrieval',
    tier: 'bronze',
    icon: 'radio',
    accent: '#56C4F5',
    criteria: { metric: 'retrieval_reviews_total', min: 1 },
  },
  {
    key: 'memory_spark',
    title: 'Orbit Spark',
    description: 'Strengthen ten memory orbits through retrieval practice.',
    category: 'retrieval',
    tier: 'bronze',
    icon: 'sparkles',
    accent: '#A78BFA',
    criteria: { metric: 'retrieval_reviews_total', min: 10 },
  },
  {
    key: 'memory_engine',
    title: 'Pulsar Engine',
    description: 'Keep a hundred signals alive through steady review.',
    category: 'retrieval',
    tier: 'gold',
    icon: 'pulse',
    accent: '#5EEAD4',
    criteria: { metric: 'retrieval_reviews_total', min: 100 },
  },
  {
    key: 'perfect_retrieval',
    title: 'Clear Horizon',
    description: 'Finish a retrieval pass with every signal remembered.',
    category: 'retrieval',
    tier: 'silver',
    icon: 'planet',
    accent: '#3DDBA8',
    criteria: { metric: 'perfect_sessions', min: 1 },
  },
  {
    key: 'ten_item_combo',
    title: 'Resonance Chain',
    description: 'Hold ten remembered signals in unbroken sequence.',
    category: 'retrieval',
    tier: 'gold',
    icon: 'git-network',
    accent: '#FBBF24',
    criteria: { metric: 'retrieval_combo', min: 10 },
  },
  // Consistency — returning to the observatory
  {
    key: 'first_study_day',
    title: 'First Light',
    description: 'Open the observatory and take your first learning action.',
    category: 'consistency',
    tier: 'bronze',
    icon: 'sunny',
    accent: '#F97316',
    criteria: { metric: 'study_days_total', min: 1 },
  },
  {
    key: 'three_day_streak',
    title: 'Triple Alignment',
    description: 'Return to study for three consecutive days.',
    category: 'consistency',
    tier: 'bronze',
    icon: 'flame',
    accent: '#FB923C',
    criteria: { metric: 'study_streak', min: 3 },
  },
  {
    key: 'seven_day_streak',
    title: 'Weeklong Orbit',
    description: 'Keep a seven-day observation streak.',
    category: 'consistency',
    tier: 'silver',
    icon: 'planet-outline',
    accent: '#F87171',
    criteria: { metric: 'study_streak', min: 7 },
  },
  {
    key: 'comeback',
    title: 'Return Signal',
    description: 'Resume exploring after at least three quiet days.',
    category: 'comeback',
    tier: 'silver',
    icon: 'return-down-back',
    accent: '#60A5FA',
    criteria: { metric: 'comeback', min: 1 },
  },
  // Roadmap — expeditions through a galaxy
  {
    key: 'path_starter',
    title: 'Expedition Launch',
    description: 'Begin charting your first constellation path.',
    category: 'roadmap',
    tier: 'bronze',
    icon: 'rocket',
    accent: '#818CF8',
    criteria: { metric: 'roadmaps_started', min: 1 },
  },
  {
    key: 'path_finisher',
    title: 'Constellation Complete',
    description: 'Illuminate every destination on a roadmap.',
    category: 'roadmap',
    tier: 'silver',
    icon: 'git-branch',
    accent: '#4ADE80',
    criteria: { metric: 'roadmaps_completed', min: 1 },
  },
  {
    key: 'deep_path',
    title: 'Deep Field Survey',
    description: 'Complete an expedition of at least ten destinations.',
    category: 'roadmap',
    tier: 'gold',
    icon: 'eye',
    accent: '#2DD4BF',
    criteria: { metric: 'roadmap_lessons_completed', min: 10 },
  },
  // Creation
  {
    key: 'first_creation',
    title: 'Stellar Forge',
    description: 'Generate your first lesson or roadmap.',
    category: 'creation',
    tier: 'bronze',
    icon: 'color-wand',
    accent: '#C084FC',
    criteria: { metric: 'creations', min: 1 },
  },
  {
    key: 'paper_learner',
    title: 'Archival Beam',
    description: 'Forge learning material from a document link.',
    category: 'creation',
    tier: 'silver',
    icon: 'document-text',
    accent: '#94A3B8',
    criteria: { metric: 'paper_learner', min: 1 },
  },
  // Mastery
  {
    key: 'mastered_ten',
    title: 'Ten Stabilized',
    description: 'Stabilize ten retrieval items at mastered status.',
    category: 'mastery',
    tier: 'gold',
    icon: 'diamond',
    accent: '#FACC15',
    criteria: { metric: 'mastered_items', min: 10 },
  },
  {
    key: 'subject_momentum',
    title: 'Galaxy Momentum',
    description: 'Illuminate at least five destinations in one expedition.',
    category: 'mastery',
    tier: 'silver',
    icon: 'trending-up',
    accent: '#34D399',
    criteria: { metric: 'lessons_in_roadmap', min: 5 },
  },
];
