import type { AchievementDefinition } from './gamificationTypes';

/** Static achievement catalog seeded idempotently into the database. */
export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // Retrieval
  {
    key: 'first_recall',
    title: 'First Recall',
    description: 'Complete your first retrieval item.',
    category: 'retrieval',
    tier: 'bronze',
    icon: 'flash',
    accent: '#38BDF8',
    criteria: { metric: 'retrieval_reviews_total', min: 1 },
  },
  {
    key: 'memory_spark',
    title: 'Memory Spark',
    description: 'Review 10 retrieval items.',
    category: 'retrieval',
    tier: 'bronze',
    icon: 'sparkles',
    accent: '#A78BFA',
    criteria: { metric: 'retrieval_reviews_total', min: 10 },
  },
  {
    key: 'memory_engine',
    title: 'Memory Engine',
    description: 'Review 100 retrieval items.',
    category: 'retrieval',
    tier: 'gold',
    icon: 'hardware-chip',
    accent: '#22D3EE',
    criteria: { metric: 'retrieval_reviews_total', min: 100 },
  },
  {
    key: 'perfect_retrieval',
    title: 'Perfect Retrieval',
    description: 'Finish a retrieval session with no forgot ratings.',
    category: 'retrieval',
    tier: 'silver',
    icon: 'checkmark-circle',
    accent: '#34D399',
    criteria: { metric: 'perfect_sessions', min: 1 },
  },
  {
    key: 'ten_item_combo',
    title: 'Ten-Item Combo',
    description: 'Remember 10 items in a row.',
    category: 'retrieval',
    tier: 'gold',
    icon: 'flame',
    accent: '#FBBF24',
    criteria: { metric: 'retrieval_combo', min: 10 },
  },
  // Consistency
  {
    key: 'first_study_day',
    title: 'First Study Day',
    description: 'Complete any learning action.',
    category: 'consistency',
    tier: 'bronze',
    icon: 'calendar',
    accent: '#F97316',
    criteria: { metric: 'study_days_total', min: 1 },
  },
  {
    key: 'three_day_streak',
    title: 'Three-Day Streak',
    description: 'Study 3 days in a row.',
    category: 'consistency',
    tier: 'bronze',
    icon: 'flame',
    accent: '#FB923C',
    criteria: { metric: 'study_streak', min: 3 },
  },
  {
    key: 'seven_day_streak',
    title: 'Seven-Day Streak',
    description: 'Study 7 days in a row.',
    category: 'consistency',
    tier: 'silver',
    icon: 'flame',
    accent: '#EF4444',
    criteria: { metric: 'study_streak', min: 7 },
  },
  {
    key: 'comeback',
    title: 'Comeback',
    description: 'Return after missing at least 3 days.',
    category: 'comeback',
    tier: 'silver',
    icon: 'arrow-undo',
    accent: '#60A5FA',
    criteria: { metric: 'comeback', min: 1 },
  },
  // Roadmap
  {
    key: 'path_starter',
    title: 'Path Starter',
    description: 'Start your first roadmap.',
    category: 'roadmap',
    tier: 'bronze',
    icon: 'map',
    accent: '#818CF8',
    criteria: { metric: 'roadmaps_started', min: 1 },
  },
  {
    key: 'path_finisher',
    title: 'Path Finisher',
    description: 'Complete your first roadmap.',
    category: 'roadmap',
    tier: 'silver',
    icon: 'flag',
    accent: '#4ADE80',
    criteria: { metric: 'roadmaps_completed', min: 1 },
  },
  {
    key: 'deep_path',
    title: 'Deep Path',
    description: 'Complete a roadmap with at least 10 lessons.',
    category: 'roadmap',
    tier: 'gold',
    icon: 'layers',
    accent: '#2DD4BF',
    criteria: { metric: 'roadmap_lessons_completed', min: 10 },
  },
  // Creation
  {
    key: 'first_creation',
    title: 'First Creation',
    description: 'Generate your first lesson or roadmap.',
    category: 'creation',
    tier: 'bronze',
    icon: 'create',
    accent: '#C084FC',
    criteria: { metric: 'creations', min: 1 },
  },
  {
    key: 'paper_learner',
    title: 'Paper Learner',
    description: 'Create learning material from a document link.',
    category: 'creation',
    tier: 'silver',
    icon: 'document-text',
    accent: '#94A3B8',
    criteria: { metric: 'paper_learner', min: 1 },
  },
  // Mastery
  {
    key: 'mastered_ten',
    title: 'Mastered Ten',
    description: 'Have 10 retrieval items reach mastered status.',
    category: 'mastery',
    tier: 'gold',
    icon: 'trophy',
    accent: '#FACC15',
    criteria: { metric: 'mastered_items', min: 10 },
  },
  {
    key: 'subject_momentum',
    title: 'Subject Momentum',
    description: 'Complete at least 5 lessons in one path.',
    category: 'mastery',
    tier: 'silver',
    icon: 'trending-up',
    accent: '#34D399',
    criteria: { metric: 'lessons_in_roadmap', min: 5 },
  },
];
